"""Historical Gap-1 reassessment script.

Do not run this for final submission. It predates the 2026-09-28 final evidence
package and can overwrite current audit matrices with stale wording. Use
scripts/audit/finalize_submission_audit.py instead.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
AUD=ROOT/'results'/'audit'
LOCAL=ROOT/'results'/'analytics'/'gap1'/'v6'
ML=ROOT/'results'/'ml'/'gap1'
RISK=ROOT/'results'/'analytics'/'gap1'/'wastage_risk_v3'

def load(path): return json.loads(path.read_text(encoding='utf-8'))
def save(path,data): path.write_text(json.dumps(data,indent=2,ensure_ascii=False),encoding='utf-8')
def read_log(path):
    raw=path.read_bytes()
    return raw.decode('utf-16',errors='replace') if b'\x00' in raw[:128] else raw.decode('utf-8',errors='replace')

def main():
    raise SystemExit("Historical script disabled; run scripts/audit/finalize_submission_audit.py for the current audit.")
    ev=load(LOCAL/'spark_gap1.json'); check=load(LOCAL/'readback_verification.json'); demand=load(ML/'demand_baseline_comparison.json'); risk=load(RISK/'pipeline.json')
    raw_tests=(RISK/'gap1_tests.log').read_bytes()
    tests=raw_tests.decode('utf-16',errors='replace') if b'\x00' in raw_tests[:128] else raw_tests.decode('utf-8',errors='replace')
    benchmark=load(ROOT/'results'/'phase3'/'scalability'/'order_items_5m_benchmark.json')
    demand_500=load(ML/'verification_20260926'/'demand_model_comparison.json')
    browser=load(ROOT/'results'/'app'/'browser_verification.json')
    regression_tests=read_log(ROOT/'results'/'regression_full.log')
    security_tests=read_log(AUD/'security_verification.log')
    assert check['status']=='PASS' and not check['failed_checks']
    assert demand['row_level_case_count']>=100 and 'Ran 8 tests' in tests and '\nOK' in tests
    assert risk['reload_smoke']['passed'] and risk['reload_smoke']['rows_with_probability']==16 and len(risk['models'])>=3
    assert benchmark['status']=='PASS' and benchmark['benchmark_rows']==5_000_000 and all(benchmark['validation'].values())
    assert demand_500['row_level_case_count']==500 and demand_500['case_sampling_method']=='evenly-spaced'
    assert 'Sunday=0' in demand_500['feature_semantics_note'] and 'Monday=0' in demand_500['feature_semantics_note']
    assert browser['all_checks_passed'] and browser['all_routes_passed']
    assert 'Ran 48 tests' in regression_tests and '\nOK' in regression_tests
    assert 'Ran 8 tests' in security_tests and '\nOK' in security_tests
    p='results/analytics/gap1/v6/spark_gap1.json'; rb='results/analytics/gap1/v6/readback_verification.json'; t='results/analytics/gap1/wastage_risk_v3/gap1_tests.log'
    fr_updates={
      'FR-xx':('PARTIAL','Menu net revenue allocates order-level discounts proportionally across item lines; cost, contribution margin, margin percent and wastage proxy calculated for 200 items. Independent pandas values for units/orders/gross/net revenue/cost/margin agree within 0.01 on all 200 items. It omits repeat rate, rating-linked attribution, promotion dependency and sales trend; costs use static menu cost.',['scripts/spark/gap1_analytics.py','scripts/python/gap1_independent.py','scripts/python/compare_gap1.py','results/python/gap1/menu_profitability.csv','results/comparison/gap1/menu_profitability_spark_python_v6.json',p,rb,t],'Complete omitted SRS dimensions and validate static cost semantics.'),
      'FR-xxi':('PARTIAL','All 200 items receive SRS classes when sufficient data exist; p75 sales/margin/waste-ratio thresholds are data-derived. New (<90 day) launches and invalid cost are explicit exceptions. Tricky-case tests cover high-pop/low-margin, low-pop/high-margin, high-waste, zero-sales, missing cost and new items.',['scripts/spark/gap1_analytics.py',p,'tests/test_gap1_analytics.py',rb],'Add item-rating, promotion and location contradictions plus UI exposure.'),
      'FR-xxiii':('PARTIAL','RFM-derived customer groups were added; synthetic source customer_segment is not used. Current grouping only uses recency/frequency/monetary, not category, promo/channel/time preferences.',['scripts/spark/gap1_analytics.py',p,rb],'Extend segments with the other SRS behavioral dimensions and independent validation.'),
      'FR-xxiv':('PARTIAL','Per-purchasing-customer recency, distinct completed-order frequency, monetary value, average order value and restaurant diversity are saved. Source customers with no completed orders are omitted.',['scripts/spark/gap1_analytics.py',p,rb],'Include zero-order customers with explicit null recency and verify all source customers.'),
      'FR-xxv':('COMPLETE','Distinct-item baskets for completed orders yield 955 retained item-pair rows from 611,135 baskets using minimum count 100.',['scripts/spark/gap1_analytics.py',p,rb,t],'Consider larger itemsets only if operationally useful.'),
      'FR-xxvi':('COMPLETE','Support, both-direction confidence and lift are calculated from keyed completed-order baskets; minimum pair count 100 and confidence threshold 0.10 are recorded.',['scripts/spark/gap1_analytics.py',p,rb,'tests/test_gap1_analytics.py'],'Thresholds are discovery cutoffs, not statistical significance tests.'),
      'FR-xxvii':('PARTIAL','A 1,222-row read-back-verified deterministic recommendation table includes observed basket-pair candidates, menu actions, RFM-targeting suggestions and low-stock reviews. Actions are rule-based, not ML or causal. A separate direction-explicit v7 rewrite stalled and is unverified.',['scripts/spark/gap1_analytics.py',p,rb,t,'results/analytics/gap1/v7/attempt.json'],'Expose recommendations in the app and complete direction-aware basket action validation.'),
      'FR-xxviii':('PARTIAL','Existing hourly restaurant-arrival forecast remains verified; this phase does not add item/category/location forecasts or other horizons.',['scripts/ml/spark_demand.py','results/ml/spark/pipeline.json'],'Add validated granular/horizon forecasts if required.'),
      'FR-xxix':('COMPLETE','Lag-168 seasonal-naive baseline and saved Spark/Python models were scored on the identical 55,200-row June-August test interval; baseline RMSE 1.9614, MAE 1.3595, R2 0.0156.',['scripts/ml/demand_baseline_comparison.py','results/ml/gap1/demand_baseline_comparison.json','results/ml/gap1/demand_prediction_cases.csv',t],'Baseline is one simple comparator; extend only if additional baseline evidence is required.'),
      'FR-xxx':('PARTIAL','Wastage quantity/cost is grouped by restaurant, item/category, month, weekday and reason. Demand, inventory, promotion, preparation quantity and exposure-normalized rates are not all integrated.',['scripts/spark/gap1_analytics.py',p,rb],'Add remaining aligned operational dimensions and denominators.'),
      'FR-xxxi':('COMPLETE','A weekly future wastage-cost risk classifier is trained and tested on a chronological panel. Target is next-week item/location cost >= training-only positive-week p75 (1,596.2); prediction is at target-week start from lagged waste/demand and known calendar/category/location. Three Spark ML models compared on validation, logistic regression selected by PR-AUC then validation F1; test is isolated. Test PR-AUC 0.0906 vs prevalence/majority baseline PR-AUC 0.0587, recall 0.5467, precision 0.0907, F1 0.1556; persistence/reload inference 16/16 passed. This is low-precision risk triage, not causal attribution.',['scripts/ml/spark_wastage_risk.py','results/analytics/gap1/wastage_risk_v3/pipeline.json','results/analytics/gap1/wastage_risk_v3/run.log','tests/test_gap1_analytics.py',t],'Treat as a screening signal only; improve precision/utility and broaden cost drivers before operational use.'),
      'FR-xxxii':('PARTIAL','Observed before/after 30-day item/location unit response and sensitivity bands are calculated for 2,992 price-change records. The association is not controlled or causal.',['scripts/spark/gap1_analytics.py',p,rb],'Account for zeros, concurrent promotions, exposure duration, and confounding; validate sensitivity classification.'),
      'FR-xxxiii':('PARTIAL','Promotion orders have revenue, order/customer counts, AOV and estimated contribution margin. Customer acquisition/repeat cohorts, wastage and post-promotion outcomes are absent.',['scripts/spark/gap1_analytics.py',p,rb],'Add acquisition/repeat/post-period and wastage measures with noncausal wording.'),
      'FR-xxxiv':('PARTIAL','A simple trap signal compares promotional cohorts with overall non-promotion averages for AOV and estimated per-order margin; no promotion met this rule in this dataset. This is uncontrolled.',['scripts/spark/gap1_analytics.py',p,rb],'Implement SRS-listed customer, wastage and substitution signals using defensible matched periods.'),
      'FR-xxxv':('PARTIAL','Existing restaurant ratings plus order-linked data are available; this phase detects temporal restaurant-level ratings but does not provide validated menu-item ratings.',['scripts/spark/gap1_analytics.py',p,rb],'Add item-linkage interpretation and profitability/sales/repeat comparison.'),
      'FR-xxxvi':('PARTIAL','Robust restaurant-day rating-mean anomaly rule (n>=30, modified-z>3) executed and detected zero candidates. It does not test all SRS cases such as identical rating bursts.',['scripts/spark/gap1_analytics.py',p,rb],'Implement burst/identical-pattern tests and validate detection on controlled fixtures.'),
      'FR-xxxvii':('PARTIAL','Restaurant-hour counts are flagged against same restaurant/hour-of-week median and MAD; 2,138 candidates saved. This is a candidate detector, not adjudicated unusual events, and omits high-value/discount/duplicate checks.',['scripts/spark/gap1_analytics.py',p,rb],'Add remaining anomaly types and review false positives.'),
      'FR-xxxix':('COMPLETE','Read-back check confirms 5,000 unique restaurant-item combinations = 25 restaurants × 200 menu items. Each includes units, gross/net revenue, estimated cost and contribution margin; output counts and schemas match.',['scripts/spark/gap1_analytics.py',p,rb,t],'Add location-specific rating/waste context only if needed for broader multi-factor analysis.'),
      'FR-xli':('PARTIAL','A descriptive 90-day inactivity indicator is computed at max observed completed-order date for customers with >=2 orders. Synthetic is_churned/last_order_date are excluded; no future label or predictive classifier is claimed.',['scripts/spark/gap1_analytics.py',p,rb],'Use multiple historical snapshots to identify change in engagement; validate an ML churn target only if future labels can be built.'),
      'FR-xlvii':('PARTIAL','Evidence-backed deterministic recommendations are persisted from observed baskets, menu classifications, RFM segments and latest low inventory records. No predictive ML recommendations are claimed; basket actions are generic candidate pairs without explicit confidence-direction wording.',['scripts/spark/gap1_analytics.py',p,rb,t,'results/analytics/gap1/v7/attempt.json'],'Add app access, resolve direction-aware basket action review, acceptance/cost tracking, and remaining evidence sources.'),
      'FR-xlviii':('PARTIAL','Menu classes drive review/visibility/cost actions and basket rules support bundles. Slow-moving criteria are not fully combined (purchase gaps, repeat rate, trend, ratings, promotion dependence).',['scripts/spark/gap1_analytics.py',p,rb],'Complete multi-factor slow-mover/menu optimization and expose in UI.'),
      'FR-xlix':('PARTIAL','Latest inventory records marked Low generate a deterministic replenishment-review recommendation; this does not use forecast/wastage risk outputs.',['scripts/spark/gap1_analytics.py',p,rb],'Connect validated demand/wastage estimates to inventory plans.'),
      'FR-l':('PARTIAL','RFM segments map to simple retention/loyalty/repeat-visit suggestions; no channel, category, timing or promotion response model is evaluated.',['scripts/spark/gap1_analytics.py',p,rb],'Add preference dimensions and evaluate targeting response.'),
      'FR-li':('PARTIAL','Validated POST /api/what-if endpoint supports price, promotion, demand, inventory and item-removal arithmetic with bounds and explicit assumptions. It has no interactive UI or preparation-quantity scenario; outputs are not forecasts.',['app/backend.py','app/what_if.py','tests/test_gap1_analytics.py',t],'Add preparation scenario and UI; extend scenario impact to wastage/cost when inputs support it.'),
    }
    comparison_path='results/ml/gap1/verification_20260926/demand_model_comparison.json'
    fr_updates['FR-xxvii']=('COMPLETE','Verified directional basket recommendations are generated from observed association rules, retained at confidence >=0.10 and lift >1.0, and served with antecedent-to-consequent wording and direction-specific confidence. They are deterministic candidates, not causal claims.',['scripts/spark/directional_basket_recommendations.py','results/analytics/gap1/v11/directional_basket_recommendations.json','app/backend.py','tests/test_app_integration.py'],'Keep candidate wording noncausal and monitor recommendation acceptance before claiming business impact.')
    fr_updates['FR-xlvii']=('PARTIAL','Evidence-backed deterministic recommendations now combine directional basket rules, menu classes, RFM segments and low-stock records; the live API/browser route exposes them. No predictive ML claim is made.',['scripts/spark/directional_basket_recommendations.py','results/analytics/gap1/v11/directional_basket_recommendations.json','app/backend.py','tests/test_app_integration.py','results/app/browser_verification.json'],'Add recommendation acceptance/cost tracking and remaining SRS evidence sources.')
    fr_updates['FR-xxix']=('COMPLETE','Freshly scored the saved Spark/Python models and seasonal-naive baseline on the identical 55,200-row held-out June-August period; a separate 500-case report records evenly spaced keyed predictions. Spark uses Sunday=0 and the saved Python model uses Monday=0, so cross-model case differences remain descriptive, not feature-equivalent.',['scripts/ml/demand_baseline_comparison.py',comparison_path,'results/ml/gap1/verification_20260926/demand_model_comparison_cases.csv'],'Retain the weekday encoding caveat; align semantics only through a separately trained and validated model.')
    fr_updates['FR-lxvi']=('COMPLETE','The responsive SPA was rendered in Microsoft Edge 154 at desktop and 390px mobile widths; all eight routes passed, with no horizontal overflow at the mobile viewport.',['app/static/index.html','app/static/app.css','app/static/app.js','results/app/browser_verification.json','results/app/browser_verification.md','results/app/browser_overview.png'],'Test additional supported browsers and accessibility before release.')
    fp=AUD/'functional_requirement_matrix.json'; fm=load(fp)
    for item in fm['requirements']:
        if item['id'] not in fr_updates: continue
        u=fr_updates[item['id']]
        status,evidence,paths,action=u
        item.update(status=status,evidence=evidence,paths=paths,test=f'Gap1 domain suite: 8 passed; canonical v4 read-back status {check["status"]}; risk model reload inference: 16/16. Full application suite re-run encountered HDFS access denied (WinError 5); see results/analytics/gap1/wastage_risk_v3/all_tests_final2.log.',action=action)
        item['test']='Full regression: 48 passed; security API suite: 8 passed; live Edge/CDP browser verification: all routes and checks passed. See results/regression_full.log, results/audit/security_verification.log, and results/app/browser_verification.json.'
    for item in fm['requirements']:
        if '33-test suite' in item.get('test',''):
            item['test']=item['test'].replace('33-test suite','48-test regression suite')
    counts={k:sum(1 for x in fm['requirements'] if x['status']==k) for k in ('COMPLETE','PARTIAL','MISSING','NOT_APPLICABLE')}
    fm['status_counts']=counts; save(fp,fm)

    mp=AUD/'srs_compliance.json'; m=load(mp)
    main_updates={
      'ANALYTICS-02':('PARTIAL','New outputs add proportional discount allocation, cost, margin, margin percent, popularity, wastage proxy and data-derived classes for all 200 menu items. Independent pandas measures agree within 0.01 for units/orders/gross/net revenue/cost/margin across all 200 items. Item ratings/repeat/promotion/trend and full UI are absent.',['scripts/spark/gap1_analytics.py','scripts/python/gap1_independent.py','scripts/python/compare_gap1.py','results/comparison/gap1/menu_profitability_spark_python_v6.json',p,rb,t],'Complete omitted SRS dimensions and expose results.'),
      'ANALYTICS-03':('PARTIAL','Behavioral RFM and a derived behavior_segment are now calculated; synthetic customer_segment labels are not used. Several segment dimensions and zero-order customers remain absent.',['scripts/spark/gap1_analytics.py',p,rb],'Add the other behavior variables and complete customer coverage.'),
      'ANALYTICS-04':('PARTIAL','Basket pairs with support/confidence/lift and deterministic candidate-combo evidence are persisted; direction-explicit recommendation rewrite stalled and is unverified. No app route/page or independent Python basket comparison yet.',['scripts/spark/gap1_analytics.py',p,rb,'results/analytics/gap1/v7/attempt.json'],'Expose results and complete UI/integration evidence.'),
      'ANALYTICS-05':('PARTIAL','Added lag-168 seasonal-naive test metrics and 500 keyed test prediction pairs; hourly restaurant target remains narrower than item/category/location/horizon SRS coverage.',['scripts/ml/demand_baseline_comparison.py','results/ml/gap1/demand_baseline_comparison.json','results/ml/gap1/demand_prediction_cases.csv'],'Add supported forecast granularity/horizons.'),
      'ANALYTICS-06':('PARTIAL','Expanded to item/category/location/month/weekday/reason cost and quantity plus historical risk ranking, and added a separately validated weekly future wastage-risk classifier (3 Spark models, chronological holdout, reload smoke). Demand/inventory/promotion/preparation aligned dimensions remain absent; classifier precision is 9.1%, so it is screening evidence only.',['scripts/spark/gap1_analytics.py',p,rb,'scripts/ml/spark_wastage_risk.py','results/analytics/gap1/wastage_risk_v3/pipeline.json'],'Complete remaining aligned operational dimensions and improve model precision/operational utility.'),
      'ANALYTICS-07':('PARTIAL','Added price response/sensitivity and promotion revenue/customer/AOV/estimated-margin cohort comparison with simple trap signal. These are uncontrolled observational comparisons; repeat/acquisition/wastage/post-period omitted.',['scripts/spark/gap1_analytics.py',p,rb],'Add missing measures and stronger observational design; do not infer causality.'),
      'ANALYTICS-08':('PARTIAL','Added restaurant-day robust rating anomaly and restaurant-hour same-hour-of-week sales candidate detection (0 and 2,138 respectively); item rating linkage and other SRS anomaly types remain incomplete.',['scripts/spark/gap1_analytics.py',p,rb],'Expand rule coverage and adjudicate examples/false positives.'),
      'ANALYTICS-09':('COMPLETE','Canonical restaurant/channel analytics plus a verified complete 25×200 menu/location grid are available; the 5,000 location-item pairs are unique and read back successfully.',['scripts/spark/gap1_analytics.py',p,rb],'Add richer location-specific rating/wastage context only for expanded analysis.'),
      'ANALYTICS-10':('PARTIAL','Added descriptive 90-day inactivity risk from observed order history, excluding synthetic churn fields. It is not a predictive churn model and does not measure an individual decline slope.',['scripts/spark/gap1_analytics.py',p,rb],'Add longitudinal engagement snapshots and validate future labels/model if appropriate.'),
      'ML-03':('PARTIAL','500 keyed held-out actual/Spark/Python predictions now saved. Same temporal test keys/target; Spark Sunday=0 vs Python Monday=0 weekday encoding is disclosed, so this is not a fully controlled feature-equivalent comparison.',['scripts/ml/demand_baseline_comparison.py','results/ml/gap1/demand_baseline_comparison.json','results/ml/gap1/demand_prediction_cases.csv'],'Align retrained feature semantics or maintain the documented encoding difference in the final evaluation.'),
    }
    main_updates['DATA-02']=('PARTIAL','A real Spark workload aggregated exactly 5,000,000 order lines: all 3,000,000 canonical v4 rows plus 2,000,000 disposable prefixed copies. All seven validations passed in 22.135 seconds without materializing the fixture or modifying canonical data; synthetic expansion is not a substitute for a 5M canonical HDFS dataset.',['scripts/spark/phase3_scalability_benchmark.py','results/phase3/scalability/order_items_5m_benchmark.json','results/phase3/scalability/order_items_5m_by_menu_item.csv'],'Measure ingestion and storage on a canonical 5M-row dataset if the SRS requires persisted-volume validation.')
    main_updates['ANALYTICS-04']=('PARTIAL','Directional association candidates now have confidence/lift per direction, are persisted under versioned HDFS v11, and are served through recommendation APIs/UI. Security/authenticated Edge checks and app integration verify the surfaced flow. Recommendation acceptance and broader independent basket comparisons remain absent.',['scripts/spark/directional_basket_recommendations.py','results/analytics/gap1/v11/directional_basket_recommendations.json','app/backend.py','tests/test_app_integration.py','results/app/browser_verification.json'],'Add independent basket comparison and recommendation acceptance/cost tracking.')
    main_updates['ANALYTICS-05']=('PARTIAL','Hourly restaurant-arrival models and the lag-168 baseline were freshly evaluated on 55,200 held-out rows; 500 evenly spaced keyed predictions are recorded. The Python model retains its Monday=0 training convention while Spark uses Sunday=0, so cross-model cases are descriptive rather than feature-equivalent.',['scripts/ml/demand_baseline_comparison.py',comparison_path,'results/ml/gap1/verification_20260926/demand_model_comparison_cases.csv'],'Add item/category/location forecasts and preserve the weekday encoding caveat unless models are retrained consistently.')
    main_updates['ML-03']=('PARTIAL','A fresh 500-case evenly spaced comparison includes keyed actual/Spark/Python predictions, disagreement, and tolerance rates: 98.4% within 0.5 and 100% within 1.0 order. Spark Sunday=0 vs Python Monday=0 remains an explicit limitation, so the report is not feature-equivalent.',['scripts/ml/demand_baseline_comparison.py',comparison_path,'results/ml/gap1/verification_20260926/demand_model_comparison_cases.csv'],'Align weekday semantics through a separately retrained model or retain the explicit limitation in evaluation.')
    main_updates['NFR-03']=('PARTIAL','Real Microsoft Edge 154/CDP verification passed all eight routes and interactive checks, including 390px responsive width, invalid-input handling, API outage messaging, and delayed recovery to 200 real menu rows. No unexpected browser/runtime errors were captured; this is not a human usability or accessibility study.',['results/app/browser_verification.json','results/app/browser_verification.md','results/app/browser_overview.png','scripts/app/verify_browser_cdp.py'],'Complete accessibility review, human usability study, and role-tailored experience review.')
    main_updates['APP-01']=('COMPLETE','Registration/login/logout, scrypt password hashing, CSRF, role/location authorization and SQLite separation remain implemented. Current security verification passed stale-session/CSRF, RBAC/location scope, exports, redaction and invalid-input checks.',['app/backend.py','app/operations_api.py','app/operational_store.py','tests/test_operations_api.py','results/audit/security_verification.log','results/app/browser_verification.json'],'Configure managed session secrets, TLS, secure cookies, backup and retention before production exposure.')
    main_updates['APP-02']=('COMPLETE','SQLite operational CRUD and role/location scope remain separate from canonical HDFS analytics. Current 48-test regression and 8-test security suite passed; the earlier authenticated Edge management checks remain preserved.',['app/operational_store.py','app/operations_api.py','tests/test_operations_api.py','results/regression_full.log','results/audit/security_verification.log','results/app/phase2/browser_verification.json'],'Add coupon code/redemption workflows if required; retain the operational/analytical data boundary.')
    main_updates['APP-03']=('PARTIAL','Authenticated Edge 154/CDP exercised all eight dashboard routes, category filtering, invalid input, outage/recovery and desktop/mobile layout. Broader SRS analytics, filters and human accessibility review remain partial.',['app/static/index.html','app/static/app.js','app/static/app.css','results/app/browser_verification.json','results/app/browser_verification.md','results/app/browser_overview.png'],'Complete missing analytical pages/features and review accessibility/supported browsers.')
    main_updates['APP-04']=('COMPLETE','The authenticated Edge run rendered the forecast form and verified invalid-hour rejection; full app integration also passed persisted-model inference against real HDFS-backed outputs.',['app/backend.py','app/static/app.js','tests/test_app_integration.py','results/app/browser_verification.json','results/ml/spark/reload_smoke.json'],'Reduce/benchmark inference latency and implement portable serving artifacts for deployment.')
    main_updates['APP-05']=('COMPLETE','Export/report APIs passed selected-format, limit and filter tests in the security suite; prior authenticated Edge checks verified downloadable CSV/report responses.',['app/operations_api.py','app/static/app.js','tests/test_operations_api.py','results/audit/security_verification.log','results/app/phase2/browser_verification.json'],'Add additional report formats only where a documented requirement calls for them.')
    main_updates['APP-06']=('PARTIAL','Current security tests verify durable audit events and password redaction; browser checks confirm readable validation, outage and recovery states. Live processing-job outcome coverage remains incomplete.',['app/operations_api.py','app/operational_store.py','tests/test_operations_api.py','results/audit/security_verification.log','results/app/browser_verification.json'],'Add audit events for live processing-job starts/completions/failures and define retention.')
    main_updates['APP-07']=('PARTIAL','The authenticated system route rendered during Edge verification; app integration asserts historical-only Spark job status and never claims active state.',['app/backend.py','app/static/app.js','tests/test_app_integration.py','results/app/browser_verification.json'],'Connect a live Spark listener/job store only if active-job monitoring is required.')
    main_updates['APP-08']=('PARTIAL','Directional basket recommendations, what-if tests, and per-case model evidence are available; the fresh 500-case report retains the weekday feature-semantics limitation and no interactive case-level agreement dashboard exists.',['app/backend.py','app/what_if.py','tests/test_gap1_analytics.py','results/ml/gap1/verification_20260926/demand_model_comparison.json','results/app/browser_verification.json'],'Complete per-case model agreement visualization and remaining recommendation evidence.')
    main_updates['TEST-01']=('COMPLETE','The full discovered app/domain/ML/comparison/scalability/adversarial/security suite passed 48 tests; the focused operational security suite passed 8 tests.',['tests/','results/regression_full.log','tests/test_operations_api.py','results/audit/security_verification.log','results/app/browser_verification.json'],'Add the remaining data-quality, hidden-data and SRS adversarial tests tracked under TEST-02 and TEST-03.')
    main_updates['TEST-02']=('PARTIAL','Automated coverage now includes HDFS-backed app contracts, 5M workload expansion, malformed/adversarial records and security boundaries. The full suite passed 48/48; broad hidden-data and all contradictory business-case scenarios remain incomplete.',['tests/','tests/test_phase3_scalability.py','tests/test_phase3_adversarial.py','tests/test_operations_api.py','results/phase3/scalability/order_items_5m_benchmark.json','results/regression_full.log','results/audit/security_verification.log'],'Add the remaining SRS tricky business cases and hidden-data scenarios.')
    main_updates['DEPLOY-01']=('PARTIAL','The local authenticated HDFS-backed app passed 48 regression tests, 8 security tests, and Edge 154/CDP route/state verification. Public serving remains blocked by fixed local HDFS/Spark/model dependencies, development-server startup, incomplete dependency lock, absent portable artifacts, and no uptime/load/production-hardening evidence.',['app/backend.py','docker-compose.yml','requirements-app.txt','results/app/browser_verification.json','results/app/browser_verification.md','results/audit/security_verification.log','results/regression_full.log','results/audit/deployment_readiness.json'],'Create portable serving artifacts, a production server/configuration, complete dependency lock, production security hardening and reproducible install/evaluator instructions.')
    for item in m['requirements']+m['nonfunctional_requirements']:
        u=main_updates.get(item['id'])
        if u: item.update(status=u[0],evidence=u[1],paths=u[2],verification=f'Executed Spark v4 read-back (all rows/schemas match), gap1 domain suite (8 passed), and local outputs. Full app integration rerun failed because Windows HDFS access returned WinError 5; see results/analytics/gap1/wastage_risk_v3/all_tests_final2.log. {item.get("verification","")}',remaining_action=u[3])
        if u: item['verification']='Full regression: 48 tests passed; security API suite: 8 tests passed; the real Edge/CDP suite passed all eight routes and all interactive/loading/error checks. Canonical v4 read-back and the saved wastage-risk-model reload checks also passed.'
        if item['id']=='NFR-04': item.update(status='COMPLETE',evidence='Hourly regression models and lag-168 seasonal-naive comparator were evaluated on the same 55,200-row chronological held-out test; model metrics improve on the baseline. Classification metrics are not applicable to this regression task.',paths=['results/ml/gap1/demand_baseline_comparison.json','scripts/ml/demand_baseline_comparison.py'],verification='Baseline RMSE 1.9614 / MAE 1.3595 / R2 0.0156; Spark GBT RMSE 1.3931 / MAE 1.0232 / R2 0.5034; test set not used for model selection.',remaining_action='Preserve baseline evidence and disclose weekday feature-encoding difference in cross-framework comparisons.')
        if item['id']=='NFR-04': item['paths']=['results/ml/gap1/verification_20260926/demand_model_comparison.json','scripts/ml/demand_baseline_comparison.py']
    for x in m.get('integrity_findings',[]):
        if x['id']=='INTEGRITY-01': x['status']='RESOLVED'; x['resolution']='Frontend money formatters now use neutral numeric values; SRS/source define no currency.'; x['evidence']=list(dict.fromkeys(x['evidence']+['app/static/app.js neutral money/money2 formatters']))
        if x['id']=='INTEGRITY-02': x['status']='RESOLVED'; x['resolution']='Added same-test-period lag-168 baseline evaluation.'; x['evidence']=list(dict.fromkeys(x['evidence']+['results/ml/gap1/demand_baseline_comparison.json']))
        if x['id']=='INTEGRITY-03': x['status']='PARTIAL'; x['resolution']='Computed profitability/classes now exist as Spark outputs, but existing UI still does not surface them.'; x['evidence']=list(dict.fromkeys(x['evidence']+[p]))
    m['status_counts']={k:sum(1 for x in m['requirements']+m['nonfunctional_requirements'] if x['status']==k) for k in ('COMPLETE','PARTIAL','MISSING','NOT_APPLICABLE')}
    m['gap1_reassessment']={'date':'2026-09-26','evidence':p,'readback':rb,'test_log':t,'note':'Only relevant analytics/ML baseline statuses were reassessed. No claims of acceptance/readiness.'}
    save(mp,m)

    dp=AUD/'deliverables_matrix.json'; d=load(dp)
    for item in d.get('deliverables',[]):
      if item['id']=='DEL-14': item.update(status='PARTIAL',evidence='Fresh comparison records exactly 500 evenly spaced keyed held-out actual/Spark/Python cases, exceeding the 100-row minimum. It reports 98.4% within 0.5 and 100% within 1.0 order, but Spark Sunday=0 vs Python Monday=0 remains a disclosed feature-semantic difference; agreement is descriptive, not controlled.',paths=['scripts/ml/demand_baseline_comparison.py',comparison_path,'results/ml/gap1/verification_20260926/demand_model_comparison_cases.csv'],action='Retain the weekday caveat or compare retrained models with aligned feature semantics in the final deliverable.')
      if item['id']=='DEL-16': item.update(status='PARTIAL',evidence='The full discovered regression suite passed 48/48, the focused security suite passed 8/8, and real Edge/CDP verification passed all routes and checks. Broader hidden-data and SRS adversarial case coverage remains incomplete.',paths=['tests/','results/regression_full.log','tests/test_operations_api.py','results/audit/security_verification.log','results/app/browser_verification.json','results/app/browser_verification.md','results/analytics/gap1/wastage_risk_v3/gap1_tests.log'],action='Add the remaining SRS adversarial and hidden-data case inventory.')
    save(dp,d)
    # Scoped, machine-readable traceability with actual command/source/output/test/limits.
    commands={
      'FR-xx':'.venv\\Scripts\\python.exe scripts\\spark\\gap1_analytics.py --version v6; .venv\\Scripts\\python.exe scripts\\spark\\export_gap1_menu.py --version v6; .venv\\Scripts\\python.exe scripts\\python\\gap1_independent.py; .venv\\Scripts\\python.exe scripts\\python\\compare_gap1.py --version v6',
      'FR-xxi':'.venv\\Scripts\\python.exe scripts\\spark\\gap1_analytics.py --version v6; .venv\\Scripts\\python.exe -m unittest tests.test_gap1_analytics -v',
      'FR-xxv':'.venv\\Scripts\\python.exe scripts\\spark\\gap1_analytics.py --version v6',
      'FR-xxvi':'.venv\\Scripts\\python.exe scripts\\spark\\gap1_analytics.py --version v6; .venv\\Scripts\\python.exe -m unittest tests.test_gap1_analytics -v',
      'FR-xxix':'.venv\\Scripts\\python.exe scripts\\ml\\demand_baseline_comparison.py',
      'FR-xxxi':'.venv\\Scripts\\python.exe scripts\\ml\\spark_wastage_risk.py --version v3',
      'FR-li':'.venv\\Scripts\\python.exe -m unittest tests.test_gap1_analytics -v',
    }
    mapping=[]
    for item in fm['requirements']:
        if item['id'] in fr_updates:
            mapping.append({'requirement_id':item['id'],'status':item['status'],'implementation_files':item['paths'],'execution_command':commands.get(item['id'],'.venv\\Scripts\\python.exe scripts\\spark\\gap1_analytics.py --version v6'),'input_source':'/dineq/processed/v4 (frozen canonical Parquet); persisted ML v1 artifacts for forecast evidence','output_path':risk['model_path']+'; '+risk['feature_path']+'; '+risk['test_prediction_path'] if item['id']=='FR-xxxi' else ev['hdfs_output_root'],'local_evidence':'results/analytics/gap1/wastage_risk_v3/pipeline.json' if item['id']=='FR-xxxi' else p,'test_evidence':t,'limitation':item['action']})
    evidence={'date':'2026-09-26','official_srs_extract':'results/audit/official_srs_extracted.txt','requirement_evidence':mapping,'spark_elapsed_seconds':ev['elapsed_seconds'],'spark_readback':check,'python_independent_pipeline':'results/python/gap1/pipeline.json','python_menu_comparison':'results/comparison/gap1/menu_profitability_spark_python_v6.json','price_sensitivity_method':'For each item/location price change with positive old/new prices: sum completed-order units in fixed 30-day pre and post windows; response ratio=(post units - pre units)/pre units divided by (new price-old price)/old price; absolute ratio >=1 high sensitivity, >=0.5 moderate, otherwise low. Observational and confounded, not causal.','promotion_trap_method':'Signal only if promo-cohort mean paid order total exceeds overall non-promo mean, while promo average estimated item contribution is lower; uncontrolled cohort, ignores customer acquisition/repeat/wastage/post-period and product substitution.','menu_classification_method':ev['menu_classification'],'basket_method':ev['basket'],'churn_rule':ev['churn'],'wastage_risk':risk,'recommendations':'Deterministic rule-based actions based on basket pairs, menu class, RFM group and latest low-stock flag; no predictive ML or causal claims. Basket action wording is generic; attempted direction-specific replacement is unverified at results/analytics/gap1/v7/attempt.json.','what_if':'POST /api/what-if does bounded price, promotion, demand, inventory, preparation and removal arithmetic with stated assumptions; scenario outputs are not forecasts.','tests':{'gap1_domain_suite':8,'gap1_domain_suite_passed':8,'full_suite_rerun':{'tests_run':25,'failures':14,'errors':2,'passed':False,'cause':'Windows HDFS client PermissionError WinError 5','log':'results/analytics/gap1/wastage_risk_v3/all_tests_final2.log'},'focused_log':t,'failed_attempts':['results/analytics/gap1/v6/all_tests_final.log (unprivileged HDFS service unavailable); initial preparation arithmetic assertion was corrected before final pass.']},'warnings':['Windows HDFS integration access failed during final full-suite rerun (WinError 5); focused gap1 suite passed.','Wastage-risk selected-model precision is 9.1%, so predicted positives are noisy and should only support triage.','Spark warned about global RFM quantile windows running through a single partition.','Spark v6 emitted a Windows temp block cleanup error after writing local run evidence; separate HDFS readback passed.','A direction-explicit recommendation rewrite stalled and was interrupted; v6 read-back-verified 1,222-row recommendation table retained. HDFS may contain partial v7 output and it was not deleted.','Exploratory HDFS gap1 versions were preserved.'],'demand_baseline':demand,'currency':'unspecified; neutral frontend amount formatting'}
    evidence['recommendations']='Versioned directional association candidates are served through the authenticated app; actions remain deterministic and noncausal. Acceptance/cost tracking and broader independent basket comparison are not implemented.'
    evidence['tests']={'gap1_domain_suite':8,'gap1_domain_suite_passed':8,'full_regression':{'tests_run':48,'failures':0,'errors':0,'passed':True,'log':'results/regression_full.log'},'security_suite':{'tests_run':8,'failures':0,'errors':0,'passed':True,'log':'results/audit/security_verification.log'},'browser_suite':{'passed':browser['all_checks_passed'],'route_count':len(browser['routes']),'json':'results/app/browser_verification.json','markdown':'results/app/browser_verification.md'},'focused_log':t}
    evidence['phase3_verification']={'benchmark':{'status':benchmark['status'],'benchmark_rows':benchmark['benchmark_rows'],'source_rows':benchmark['source_rows'],'supplemental_rows':benchmark['supplemental_rows'],'operation_runtime_seconds':benchmark['operation_runtime_seconds'],'evidence':'results/phase3/scalability/order_items_5m_benchmark.json','aggregate_csv':'results/phase3/scalability/order_items_5m_by_menu_item.csv'},'demand_model_comparison':{'cases':demand_500['row_level_case_count'],'sampling':demand_500['case_sampling_method'],'weekday_semantics_note':demand_500['feature_semantics_note'],'evidence':comparison_path},'browser':{'browser':browser['browser'],'passed':browser['all_checks_passed'],'screenshot':browser['screenshot'],'evidence':'results/app/browser_verification.json'}}
    m['gap1_reassessment']['phase3_verification']=evidence['phase3_verification']
    save(mp,m)
    for record in mapping:
      if record['requirement_id']=='FR-xxix': record['local_evidence']=comparison_path
    evidence['requirement_evidence']=mapping
    save(ROOT/'results'/'analytics'/'gap1'/'implementation_evidence.json',evidence)
    print(json.dumps({'functional_counts':counts,'main_counts':m['status_counts'],'reassessed':len(mapping),'evidence':'results/analytics/gap1/implementation_evidence.json'},indent=2))

if __name__=='__main__': main()
