"""Build presentation-only photo mappings from the canonical menu CSVs.

Run from the repository root:
  .venv\Scripts\python.exe -B frontend/scripts/build-dish-images.py
No dataset, backend, or business metrics are modified.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

FRONTEND = Path(__file__).resolve().parents[1]
ROOT = FRONTEND.parent
CATEGORY_ASSETS = {
    'Burgers': 'burgers', 'Pizza': 'pizza', 'Pakistani': 'pakistani',
    'BBQ': 'bbq', 'Beverages': 'beverages', 'Desserts': 'desserts',
    'Chinese': 'chinese', 'Fast Food': 'fast-food', 'Breakfast': 'breakfast',
    'Salads': 'salads', 'Pasta': 'pasta', 'Seafood': 'seafood',
    'Sandwiches': 'sandwiches', 'Rice': 'rice', 'Coffee & Tea': 'coffee-tea',
}


def read_csv(name: str) -> list[dict[str, str]]:
    with (ROOT / 'data' / 'generated' / name).open(encoding='utf-8-sig', newline='') as source:
        return list(csv.DictReader(source))


def main() -> None:
    categories = {r['category_id']: r['category_name'] for r in read_csv('menu_categories.csv')}
    items = read_csv('menu_items.csv')
    photos = {}
    for item in items:
        category = categories[item['category_id']]
        slug = CATEGORY_ASSETS[category]
        src = f'/images/dishes/catalog/{slug}.jpg'
        if not (FRONTEND / 'public' / src.lstrip('/')).is_file():
            raise FileNotFoundError(f'Missing photo for {category}: {src}')
        if item['menu_item_id'] in photos:
            raise ValueError(f'Duplicate menu ID: {item["menu_item_id"]}')
        photos[item['menu_item_id']] = {'src': src, 'name': item['item_name'], 'category': category}
    header = (
        '// AUTO-GENERATED by scripts/build-dish-images.py from data/generated/menu_items.csv.\n'
        '// Representative category photos for the canonical menu IDs; numbered variants share photos.\n'
        '// Presentation only: no prices, metrics, or inferred ingredients.\n'
        'export const DISH_IMAGES: Record<string, { src: string; name: string; category: string }> = '
    )
    destination = FRONTEND / 'src' / 'generated' / 'dishImages.generated.ts'
    destination.write_text(header + json.dumps(photos, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    print(f'Mapped {len(photos)}/{len(items)} menu items to {len(set(p["src"] for p in photos.values()))} category photos.')


if __name__ == '__main__':
    main()
