"""Build direction-safe deterministic recommendations from gap1 Spark outputs."""
import argparse,json,sys,time
from pathlib import Path
from pyspark.sql import functions as F,Window
sys.path.insert(0,str(Path(__file__).resolve().parent))
from common import HDFS,spark,save_json
ROOT=Path(__file__).resolve().parents[2]
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--input-version',default='v6');ap.add_argument('--version',default='v7');ap.add_argument('--min-confidence',type=float,default=.1);a=ap.parse_args()
    s=spark('DineIQ-Gap1-Recommendations');s.sparkContext.setLogLevel('ERROR');beg=time.perf_counter()
    try:
        base=f'{HDFS}/dineq/results/gap1/{a.input_version}'
        rules=s.read.parquet(base+'/basket_rules'); menu=s.read.parquet(base+'/menu_profitability'); rfm=s.read.parquet(base+'/customer_rfm'); inv=s.read.parquet(f'{HDFS}/dineq/processed/v4/inventory'); items=s.read.parquet(f'{HDFS}/dineq/processed/v4/menu_items')
        rec_basket=(rules.where((F.greatest('confidence_a_to_b','confidence_b_to_a')>=a.min_confidence)&(F.greatest('lift_a_to_b','lift_b_to_a')>1))
          .select(F.lit('market basket').alias('source'),F.lit('Evaluate as a candidate combo; association is not causal').alias('action'),F.concat_ws(' + ',F.col('item_a_name'),F.col('item_b_name')).alias('subject'),F.concat_ws('; ',F.concat(F.lit('pair_count='),F.col('pair_count').cast('string')),F.concat(F.lit('support='),F.round('support',6).cast('string')),F.concat(F.lit('confidence A→B='),F.round('confidence_a_to_b',4).cast('string')),F.concat(F.lit('confidence B→A='),F.round('confidence_b_to_a',4).cast('string')),F.concat(F.lit('lift='),F.round(F.greatest('lift_a_to_b','lift_b_to_a'),4).cast('string'))).alias('evidence'))
          .orderBy(F.desc(F.greatest('lift_a_to_b','lift_b_to_a')),F.desc('pair_count')).limit(100))
        rec_menu=(menu.where(F.col('performance_class').isin('Hidden Opportunity','Low Performer','Volume Driver')).select(F.lit('menu performance').alias('source'),F.when(F.col('performance_class')=='Hidden Opportunity','test targeted visibility').when(F.col('performance_class')=='Volume Driver','review portion and cost margin').otherwise('review demand and cost before removal').alias('action'),F.col('item_name').alias('subject'),F.concat_ws('; ',F.concat(F.lit('class='),F.col('performance_class')),F.concat(F.lit('units='),F.coalesce(F.col('units_sold').cast('string'),F.lit('0'))),F.concat(F.lit('contribution margin='),F.coalesce(F.round('contribution_margin',2).cast('string'),F.lit('unknown')))).alias('evidence')))
        rec_customer=(rfm.groupBy('behavior_segment').agg(F.count('*').alias('customers')).select(F.lit('customer behavior').alias('source'),F.when(F.col('behavior_segment')=='At risk (90d inactive)','review engagement with a retention offer').when(F.col('behavior_segment')=='High-value loyal','consider loyalty recognition').when(F.col('behavior_segment')=='One-time customer','consider a measured repeat-visit offer').otherwise('tailor communication to observed engagement').alias('action'),F.col('behavior_segment').alias('subject'),F.concat_ws('; ',F.concat(F.lit('customers='),F.col('customers').cast('string')),F.lit('deterministic RFM segment')).alias('evidence')))
        latest=(inv.withColumn('rn',F.row_number().over(Window.partitionBy('restaurant_id','menu_item_id').orderBy(F.desc('record_date')))).where('rn=1').join(items.select('menu_item_id','item_name'),'menu_item_id','left'))
        rec_inventory=(latest.where(F.col('stock_status')=='Low').select(F.lit('inventory').alias('source'),F.lit('review replenishment against recent consumption').alias('action'),F.concat_ws(' @ ',F.col('item_name'),F.col('restaurant_id')).alias('subject'),F.concat_ws('; ',F.concat(F.lit('record_date='),F.col('record_date').cast('string')),F.concat(F.lit('closing_stock='),F.col('closing_stock').cast('string')),F.concat(F.lit('reorder_level='),F.col('reorder_level').cast('string'))).alias('evidence')))
        out=rec_basket.unionByName(rec_menu).unionByName(rec_customer).unionByName(rec_inventory);path=f'{HDFS}/dineq/results/gap1/{a.version}/recommendations';out.write.mode('errorifexists').parquet(path);rows=s.read.parquet(path).cache();n=rows.count()
        ev={'input':'Spark gap1 '+a.input_version+' outputs from canonical '+f'{HDFS}/dineq/processed/v4','output_path':path,'row_count':n,'readback_rows':n,'min_confidence':a.min_confidence,'basket_rule':'only candidate combo if lift>1 and max of both directional confidence values meets threshold; outputs both confidence directions','recommendation_types':{'basket':'candidate combo, association not causal','menu':'deterministic class-based review actions','customer':'deterministic RFM segment suggestions','inventory':'latest low-stock review using canonical v4 inventory'},'prediction_claim':False,'elapsed_seconds':round(time.perf_counter()-beg,3),'sample':[json.loads(x) for x in rows.limit(12).toJSON().collect()]}
        dest=ROOT/'results'/'analytics'/'gap1'/a.version;dest.mkdir(parents=True,exist_ok=True);save_json(dest/'recommendations.json',ev);print(json.dumps(ev,indent=2,default=str));rows.unpersist()
    finally:s.stop()
if __name__=='__main__':main()
